version: '3'
networks:
  spark-net:
    external:
      name: spark-net

services:
  spark-master:
    image: spark-master:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    # volumes: 
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - spark-net  

  spark-worker-1:
    image: spark-worker:latest
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    # volumes:
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - spark-net  

  spark-worker-2:
    image: spark-worker:latest
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    # volumes:  
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - spark-net

  spark-worker-3:
    image: spark-worker:latest
    container_name: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    # volumes:  
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - spark-net

  spark-worker-4:
    image: spark-worker:latest
    container_name: spark-worker-4
    depends_on:
      - spark-master
    ports:
      - "8084:8081"
    # volumes:  
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - spark-net

  spark-history-server:
    image: spark-history-server:latest
    container_name: spark-history-server
    depends_on:
      - spark-master
    ports:
      - "18081:18081"
    volumes:
      - ./tmp/spark-events-local:/tmp/spark-events
    networks:
      - spark-net

  spark-jupyterlab:
    image: spark-jupyterlab:latest
    container_name: spark-jupyterlab
    ports:
      - 8888:8888
    volumes:
      - ./jupyterlab:/opt/workspace
    networks:
      - spark-net